// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/meteogram-redesign/Current.tsx": () => import("../components/mockups/meteogram-redesign/Current.tsx"),
  "./components/mockups/meteogram-redesign/EditorialForecastStrip.tsx": () => import("../components/mockups/meteogram-redesign/EditorialForecastStrip.tsx"),
  "./components/mockups/meteogram-redesign/QuietWeatherMap.tsx": () => import("../components/mockups/meteogram-redesign/QuietWeatherMap.tsx"),
  "./components/mockups/meteogram-redesign/SailingCockpit.tsx": () => import("../components/mockups/meteogram-redesign/SailingCockpit.tsx"),
  "./components/mockups/meteogram-redesign/WeatherIconGallery.tsx": () => import("../components/mockups/meteogram-redesign/WeatherIconGallery.tsx")
};
